spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:local
    username: sa
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.oms: DEBUG
    org.hibernate.SQL: DEBUG